[2022-03-16 16:41:10] INFO (exp_logger/MainThread) No Edges vs. Edges in training set = 1.0300164331166037
exp/Youshu
[2022-03-16 16:41:10] ERROR (exp_logger/MainThread) Traceback (most recent call last):
  File "C:\Users\orteg\Downloads\BGGN-main\run_exp.py", line 58, in main
    runner.test()
  File "C:\Users\orteg\Downloads\BGGN-main\runner\bggn_runner.py", line 360, in test
    load_model(model, model_file, self.device)
  File "C:\Users\orteg\Downloads\BGGN-main\utils\train_helper.py", line 48, in load_model
    model_snapshot = torch.load(file_name, map_location=device)
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/Youshu\\model_snapshot_0000050.pth'
INFO  | 2022-03-16 16:41:10,867 | bggn_runner.py            | line 157  : No Edges vs. Edges in training set = 1.0300164331166037
ERROR | 2022-03-16 16:41:10,925 | run_exp.py                | line 60   : Traceback (most recent call last):
  File "C:\Users\orteg\Downloads\BGGN-main\run_exp.py", line 58, in main
    runner.test()
  File "C:\Users\orteg\Downloads\BGGN-main\runner\bggn_runner.py", line 360, in test
    load_model(model, model_file, self.device)
  File "C:\Users\orteg\Downloads\BGGN-main\utils\train_helper.py", line 48, in load_model
    model_snapshot = torch.load(file_name, map_location=device)
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\orteg\Anaconda3\envs\bggn_env\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'exp/Youshu\\model_snapshot_0000050.pth'